---

- name: "getent hosts added to inventory"
  ansible.builtin.add_host:
    name: "{{ item }}"
    groups: "{{ outside_item.ansible_facts.getent_netgroup.keys() | list | flatten | join }}"
  with_items:
    - "{{ outside_item.ansible_facts.getent_netgroup.values() | list | flatten | replace('(', '') | replace(')', '') | replace(',,', '') }}"
  tags:
     - fetch-netgroup-info

