--- 

- name: "find totp files"
  ansible.builtin.find:
    paths: /home
    patterns: "^totp$"
    use_regex: yes
    file_type: file
    recurse: yes
    excludes: "mysql,nginx"
  register: totpfiles_found
  tags:
    - get-totp-files

- name: "debug totpfiles_found"
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ totpfiles_found.files }}"
  tags:
    - get-totp-files

#- name: "fetch totp files"
#  ansible.builtin.fetch:
#    src: "{{ item.path }}"
#    dest: "{{ fetch_totp_dir }}"
#  loop: "{{ totpfiles_found.files }}"
#  tags:
#    - get-totp-files

- name: "slurp totp files"
  ansible.builtin.slurp:
    src: "{{ item.path }}"
  loop: "{{ totpfiles_found.files }}"
  register: totpfiles_content
  tags:
    - get-totp-files

- name: "debug totpfiles_content"
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ totpfiles_content.results }}"
  tags:
    - get-totp-files

- name: "set fact for slurped totpfiles_content"
  ansible.builtin.set_fact:
    totp_content: "{{ totpfiles_content.results }}"
  tags:
    - get-totp-files


