---

# this will run on host containing pubkeys in user home dirs
# look for all pubkeys under home dir
- name: "find ssh public key files"
  ansible.builtin.find:
    paths: /home
    patterns: "^id_.*pub$"
    use_regex: yes
    file_type: file
    recurse: yes
    excludes: "mysql,nginx"
  register: sshpubkeys_found
  tags:
    - get-ssh-publickey

- name: "debug sshpubkeys_found"
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ sshpubkeys_found.files }}"
  tags:
   - get-ssh-publickey

- name: "slurp pub keys"
  ansible.builtin.slurp:
    src: "{{ item.path }}"
  loop: "{{ sshpubkeys_found.files }}"
  register: sshpubkeys_content
  tags:
    - get-ssh-publickey

- name: "debug sshpubkeys_content"
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ sshpubkeys_content.results }}"
  tags:
    - get-ssh-publickey

- name: "set fact for slurped sshpubkeys_content"
  ansible.builtin.set_fact:
    sshpk_content: "{{ sshpubkeys_content.results }}"
  tags:
    - get-ssh-publickey


